---
meta:
  name:    nats
  release: nats
  target:  sw
  url:     https://ci.starkandwayne.com

  initial_version: 1.1.0

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  starkandwayne
    repo:   nats
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook: unknown
    channel: '#vault'
